//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalCookBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredients
    {
        public long id { get; set; }
        public long recipeId { get; set; }
        public string body { get; set; }
        public Nullable<long> ordering { get; set; }
    
        public virtual recipes recipes { get; set; }
    }
}
